import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const templateRoot = new URL("../", import.meta.url);

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the 股基罗盘 dashboard", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>股基罗盘｜AI 持仓分析助手<\/title>/);
  assert.match(html, /正在检查登录状态/);
  assert.doesNotMatch(html, /我的持仓/);
  assert.doesNotMatch(html, /匿名持仓库/);
  assert.doesNotMatch(html, /268\.36|82%|先稳仓/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton|Your site is taking shape/i);
});

test("keeps the Hallmark workbench structure and removes starter preview dependencies", async () => {
  const [page, layout, packageJson, marketData, styles] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../lib/market-data.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  assert.match(page, /function HomeDashboard/);
  assert.match(page, /function AssetOverview/);
  assert.match(page, /scope="全部持仓"/);
  assert.match(page, /scope="股票持仓"/);
  assert.match(page, /scope="基金持仓"/);
  assert.match(page, /<dt>今日盈亏<\/dt>/);
  assert.match(page, /<dt>累计盈亏<\/dt>/);
  assert.match(page, /<dt>累计收益率<\/dt>/);
  assert.match(page, /总资产仅统计网站已录入持仓，不含未录入现金/);
  assert.match(page, /dayProfit \+= \(price - previousClose\) \* quantity/);
  assert.match(page, /totalProfit \+= profit/);
  assert.match(page, /function MarketPage/);
  assert.match(page, /label: "行情"/);
  assert.match(page, /label: "美股"/);
  assert.match(page, /沪深京市场/);
  assert.match(page, /market-index-range/);
  assert.match(page, /function ASectorHeatmap/);
  assert.match(page, /行业热力图/);
  assert.match(page, /涨幅前 24 \+ 跌幅前 24，共 48 个行业样本/);
  assert.match(page, /目标 48 个行业样本，本轮成功同步.*个/);
  assert.match(page, /面积参考成交额/);
  assert.match(page, /function buildSectorTreemap/);
  assert.match(page, /Math\.sqrt\(Math\.max\(item\.amount \?\? minimumAmount, minimumAmount\)\)/);
  assert.match(page, /layout\(sortedNodes, 0, 0, canvasWidth, canvasHeight\)/);
  assert.match(page, /new ResizeObserver\(updateRatio\)/);
  assert.match(page, /style=\{\{ left: `\$\{x\}%`, top: `\$\{y\}%`, width: `\$\{width\}%`, height: `\$\{height\}%` \}\}/);
  assert.match(page, /强涨/);
  assert.match(page, /强跌/);
  assert.doesNotMatch(page, /items\.slice\(0, 24\)|36 格/);
  assert.match(page, /成交额榜/);
  assert.match(page, /全部股票/);
  assert.match(page, /股票排行方式/);
  assert.match(page, /rankDirection/);
  assert.match(page, /升序 ↑/);
  assert.match(page, /降序 ↓/);
  assert.match(page, /市场宽度/);
  assert.match(page, /沪深京实时前 20/);
  assert.match(page, /<th>排名<\/th><th>名称\/代码<\/th><th>最新价<\/th><th>涨跌额<\/th><th>涨跌幅<\/th>/);
  assert.match(page, /股票三榜各显示实时前 20/);
  assert.match(page, /市场宽度样本暂时未返回/);
  assert.match(page, /宽度样本.*breadthSampleSize/);
  assert.match(page, /breadthItems/);
  assert.match(page, /成交活跃宽度样本/);
  assert.match(page, /三榜去重样本/);
  assert.match(page, /宽度与行业每分钟最多更新一次/);
  assert.match(page, /市场宽度优先取 500 只成交活跃股票/);
  assert.match(page, /行业热力图取涨幅前 24 与跌幅前 24/);
  assert.doesNotMatch(page, /30 只热门股样本|30 股样本/);
  assert.match(page, /includeAMarket: true/);
  assert.match(page, /不使用固定股票或行业补位/);
  assert.match(page, /搜索股票代码或名称/);
  assert.match(page, /点击股票名称可展开详情/);
  assert.match(page, /仅查看行情，不加入持仓、不调用 AI/);
  assert.match(page, /function StocksPage/);
  assert.match(page, /股票自选最多保存 30 只/);
  assert.match(page, /stock-watchlist-table/);
  assert.match(page, /method: "DELETE"/);
  assert.match(page, /function StockHoldingTable/);
  assert.match(page, /<th>股票<\/th><th>今盈亏<\/th><th>总盈亏<\/th><th>总收益率<\/th><th>现价<\/th><th>成本<\/th><th>数量<\/th><th>市值\/仓位<\/th><th>行情<\/th>/);
  assert.match(page, /先看盈亏结果，再核对价格、成本和仓位/);
  assert.match(page, /\(price - previousClose\) \* quantity/);
  assert.match(page, /\(price - cost\) \* quantity/);
  assert.match(page, /function FundsPage/);
  assert.match(page, /function FundManagerResearch/);
  assert.match(page, /function FundOverlapResearch/);
  assert.match(page, /function FundHistoryResearch/);
  assert.match(page, /fetch\("\/api\/funds"/);
  assert.match(page, /fetch\("\/api\/fund-history"/);
  assert.match(page, /读取现任经理、任职期与本轮回报/);
  assert.match(page, /按最新定期报告的前十大股票持仓计算/);
  assert.match(page, /至少需要两只基金/);
  assert.match(page, /逐只基金按单位净值日收益形态计算，不混合不同基金样本/);
  assert.match(page, /<p>\{result\.note\}<\/p>/);
  assert.match(page, /function NewsPage/);
  assert.match(page, /聚合多家 7×24 快讯和监管政策/);
  assert.match(page, /无需先添加持仓/);
  assert.match(page, /\["全部", "快讯", "政策", "持仓"\]/);
  assert.match(page, /同一事件合并来源，不复制媒体全文/);
  assert.match(page, /sourceCount > 1/);
  assert.match(page, /fetch\("\/api\/news", \{ credentials: "same-origin", cache: "no-store" \}\)/);
  assert.match(page, /function UsPage/);
  assert.match(page, /includeUsMarket: true/);
  assert.match(page, /美股三大指数/);
  assert.match(page, /先看三大指数，再看常看的公司/);
  assert.match(page, /fetch\("\/api\/us-watchlist", \{ credentials: "same-origin", cache: "no-store" \}\)/);
  assert.match(page, /method: "POST"/);
  assert.match(page, /method: "DELETE"/);
  assert.match(page, /刷新和重启后仍保留/);
  assert.match(page, /已加入并长期保存到本设备/);
  assert.match(page, /不会进入 AI 持仓分析/);
  assert.match(page, /清除浏览器网站数据后将无法找回/);
  assert.doesNotMatch(page, /useState<Array<\{ symbol: string; name: string \}>>\(\[\{ symbol: "NVDA"/);
  assert.match(page, /const LIVE_MARKET_REFRESH_MS = 30 \* 1000/);
  assert.match(page, /const IDLE_MARKET_REFRESH_MS = 5 \* 60 \* 1000/);
  assert.match(page, /const MANUAL_REFRESH_COOLDOWN_MS = 30 \* 1000/);
  assert.match(page, /function marketRefreshInterval/);
  assert.match(page, /"America\/New_York"/);
  assert.match(page, /document\.addEventListener\("visibilitychange"/);
  assert.match(page, /搜代码或名称，点击结果即可加入/);
  assert.match(page, /kind: "美股"/);
  assert.match(page, /例如 MSFT 或 微软/);
  assert.doesNotMatch(page, /us-add-form/);
  assert.match(page, /热门股成交榜/);
  assert.match(page, /热门股涨幅榜/);
  assert.match(page, /热门股跌幅榜/);
  assert.match(page, /function formatChangeAmount/);
  assert.match(page, /us-move-table/);
  assert.match(page, /<th>名称\/代码<\/th><th>最新价<\/th><th>涨跌额<\/th><th>涨跌幅<\/th>/);
  assert.match(page, /不代表全市场排名/);
  assert.match(page, /function AddHoldingDialog/);
  assert.match(page, /transaction-form-grid/);
  assert.match(page, /transaction-ledger-summary/);
  assert.match(styles, /\.transaction-form-grid\s*\{/);
  assert.match(styles, /\.transaction-side-in\s*\{/);
  assert.match(page, /基金代码或名称/);
  assert.match(page, /当前持有金额（元）/);
  assert.match(page, /持有收益（元）/);
  assert.match(page, /开始 AI 分析/);
  assert.match(page, /添加持仓后可用/);
  assert.match(page, /基本面 \/ 估值/);
  assert.match(page, /function verificationLabel/);
  assert.match(page, /Math\.max\(2, sourceCount\).*源验证/);
  assert.match(page, /来源冲突/);
  assert.match(page, /最新共同收盘偏差/);
  assert.match(page, /量化风险/);
  assert.match(page, /fetch\("\/api\/fundamentals"/);
  assert.match(page, /fetch\("\/api\/risk"/);
  assert.match(page, /复制数据明细 JSON/);
  assert.match(page, /明天（下一交易日）/);
  assert.match(page, /重点看.*analysis\.tomorrow\.focusAsset/);
  assert.match(page, /建议怎么做/);
  assert.match(page, /AI 分析小组的三句结论/);
  assert.match(page, /看盘面、看持仓、再把风险挑出来/);
  assert.match(page, /item\.role/);
  assert.match(page, /根据：\{item\.evidence\}/);
  assert.match(page, /接下来可以怎么做/);
  assert.match(page, /为什么这么判断/);
  assert.match(page, /最可能/);
  assert.match(page, /如果走强/);
  assert.match(page, /如果走弱/);
  assert.match(page, /什么情况说明刚才看错了/);
  assert.match(page, /plainStance/);
  assert.match(styles, /\.analysis-data-grid\s*\{/);
  assert.match(styles, /\.analysis-action-list\s*\{/);
  assert.match(styles, /\.forecast-scenarios\s*\{/);
  assert.match(styles, /\.tomorrow-card\s*\{/);
  assert.match(styles, /\.tomorrow-probabilities\s*\{/);
  assert.match(styles, /\.action-heading\s*\{/);
  assert.match(page, /mode: "evidence"/);
  assert.match(page, /\/api\/search/);
  assert.match(page, /function AiConsentDialog/);
  assert.match(page, /\/api\/market/);
  assert.match(page, /\/api\/news/);
  assert.match(page, /\/api\/analysis/);
  assert.match(page, /交易时段每 30 秒，其他时段每 5 分钟/);
  assert.match(page, /页面转到后台会暂停，回来立即更新/);
  assert.match(page, /确认开始 AI 联合研判/);
  assert.match(page, /交给外部 AI 服务/);
  assert.doesNotMatch(page, /DeepSeek/i);
  assert.match(styles, /\.asset-icon,\s*\.us-symbol\s*\{[^}]*display: inline-grid;[^}]*place-content: center;[^}]*line-height: 1;[^}]*text-align: center;/s);
  assert.match(styles, /\.asset-name > div > span/);
  assert.match(styles, /\.fund-research-title > div > span/);
  assert.doesNotMatch(styles, /\.asset-name span\s*\{/);
  assert.doesNotMatch(styles, /\.fund-research-title span\s*,/);
  assert.match(styles, /\.dialog\s*\{[^}]*position: fixed;[^}]*inset: 0;[^}]*height: fit-content;[^}]*margin: auto;/s);
  assert.match(styles, /max-height: min\(48rem, calc\(100dvh - 2rem\)\)/);
  assert.match(styles, /\.market-strip\s*\{[^}]*background: var\(--sidebar\);[^}]*color: var\(--sidebar-text\);/s);
  assert.doesNotMatch(styles, /\.market-strip\s*\{[^}]*background: var\(--text-strong\)/s);
  assert.match(styles, /\.market-strip b\s*\{[^}]*var\(--sidebar-text\) 80%[^}]*font-weight: 600/s);
  assert.match(styles, /\.market-strip \.market-note\s*\{[^}]*position: sticky;[^}]*right: 0;[^}]*background: var\(--sidebar\)/s);
  assert.match(styles, /\.sector-heatmap\s*\{[^}]*position: relative;[^}]*overflow: hidden;[^}]*background: var\(--color-sector-grid\);/s);
  assert.match(styles, /\.sector-heat-tile\s*\{[^}]*position: absolute;[^}]*border: var\(--space-3xs\) solid var\(--color-sector-grid\);/s);
  assert.match(styles, /\.sector-heat-tile\.up\.strong\s*\{[^}]*background: var\(--color-sector-up-strong\);/s);
  assert.match(styles, /\.sector-heat-tile\.down\.strong\s*\{[^}]*background: var\(--color-sector-down-strong\);/s);
  assert.match(styles, /\.sector-heat-scale\s*\{[^}]*grid-template-columns: repeat\(7, minmax\(0, 1fr\)\);/s);
  assert.match(styles, /\.sector-heat-scale span\s*\{[^}]*display: flex;[^}]*min-height: 2\.15rem;[^}]*align-items: center;[^}]*justify-content: center;[^}]*line-height: 1;/s);
  assert.match(styles, /\.sector-heat-scale b\s*\{[^}]*line-height: 1;/s);
  assert.match(styles, /\.sector-heat-scale small\s*\{[^}]*line-height: 1;/s);
  assert.doesNotMatch(page, /268\.36|82%|先稳仓/);
  assert.match(layout, /股基罗盘｜AI 持仓分析助手/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
  assert.doesNotMatch(page, /_sites-preview/);
  assert.match(marketData, /fetchAStockRank\("f3", true, "涨幅榜"\)/);
  assert.match(marketData, /fetchAStockRank\("f3", false, "跌幅榜"\)/);
  assert.match(marketData, /fetchAStockRank\("f6", true, "成交额榜"\)/);
  assert.match(marketData, /async function fetchSinaAStockRank/);
  assert.match(marketData, /Market_Center\.getHQNodeData/);
  assert.match(marketData, /node: "hs_a"/);
  assert.match(marketData, /export function parseSinaAStockRow/);
  assert.match(marketData, /fetchEastmoneyAStockRank/);
  assert.match(marketData, /const A_STOCK_RANK_LIMIT = 20/);
  assert.match(marketData, /const A_BREADTH_SAMPLE_SIZE = 500/);
  assert.match(marketData, /async function fetchSinaABreadthSample/);
  assert.match(marketData, /sort: "amount"/);
  assert.match(marketData, /fetchEastmoneyABreadthSample/);
  assert.match(marketData, /withMarketCache\("a:breadth", fetchABreadthSample, A_BREADTH_CACHE_TTL_MS, A_BREADTH_STALE_TTL_MS\)/);
  assert.match(marketData, /const A_BREADTH_CACHE_TTL_MS = 60 \* 1000/);
  assert.match(marketData, /const A_BREADTH_STALE_TTL_MS = 30 \* 60 \* 1000/);
  assert.match(marketData, /url\.searchParams\.set\("pz", String\(A_STOCK_RANK_LIMIT\)\)/);
  assert.match(marketData, /url\.searchParams\.set\("pz", String\(A_BREADTH_SAMPLE_SIZE\)\)/);
  assert.match(marketData, /slice\(0, A_STOCK_RANK_LIMIT\)/);
  assert.match(marketData, /async function fetchASectors/);
  assert.match(marketData, /const A_SECTOR_SAMPLE_PER_SIDE = 24/);
  assert.match(marketData, /const A_SECTOR_SAMPLE_TARGET = A_SECTOR_SAMPLE_PER_SIDE \* 2/);
  assert.match(marketData, /async function fetchSinaASectors/);
  assert.match(marketData, /newSinaHy\.php/);
  assert.match(marketData, /new TextDecoder\("gbk"\)/);
  assert.match(marketData, /export function parseSinaIndustryPayload/);
  assert.match(marketData, /code === "new_stock"/);
  assert.match(marketData, /numberOrNull\(fields\[5\]\)/);
  assert.match(marketData, /numberOrNull\(fields\[7\]\)/);
  assert.match(marketData, /fetchEastmoneyASectors/);
  assert.match(marketData, /fetchEastmoneyASectorRank\(true\)/);
  assert.match(marketData, /fetchEastmoneyASectorRank\(false\)/);
  assert.match(marketData, /selectASectorExtremes\(await fetchSinaASectors\(\)\)/);
  assert.match(marketData, /selectASectorExtremes\(await fetchEastmoneyASectors\(\)\)/);
  assert.match(marketData, /describeAMarketSource/);
  assert.match(marketData, /Promise\.allSettled/);
  assert.match(marketData, /sectorResult\.value\.items : \[\]/);
  assert.match(marketData, /withMarketCache\("a:sectors", fetchASectors, A_SECTOR_CACHE_TTL_MS, A_SECTOR_STALE_TTL_MS\)/);
  assert.match(marketData, /const A_SECTOR_CACHE_TTL_MS = 60 \* 1000/);
  assert.match(marketData, /const A_SECTOR_STALE_TTL_MS = 30 \* 60 \* 1000/);
  assert.match(marketData, /const MARKET_CACHE_TTL_MS = 15 \* 1000/);
  assert.match(marketData, /async function withMarketCache/);
  assert.match(marketData, /withMarketCache\("a:overview"/);
  assert.match(marketData, /withMarketCache\("us:rankings"/);
  assert.doesNotMatch(marketData, /fetchAPopularSample|fetchASectorProxies/);
  await access(new URL("tokens.css", templateRoot));
  await access(new URL(".hallmark/preflight.json", templateRoot));
});
